remote_theme: mmistakes/so-simple-theme

title: AnantaDurgaPrasad
email: anantadurgaprasad@gmail.com
description: "This is DevOps Blog Site"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://anantadurgaprasad.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"


# Liquid
liquid:
  error_mode: strict

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

author:
  name: Ananta Durga Prasad
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/312Ananta
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/anantadurgaprasad
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/312Ananta
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/anantadurgaprasad
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/ananta-durga-prasad-111b7b244/
    icon: fab fa-linkedin